# Generated by Django 4.2.4 on 2023-08-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='availability',
            field=models.CharField(choices=[('Available', 'available'), ('Not available', 'not available')], default='Available', max_length=50),
        ),
    ]
