# Generated by Django 4.2.4 on 2023-08-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_alter_post_price_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimages",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
