# Generated by Django 4.2.4 on 2023-08-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0006_alter_postimages_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=9, null=True
            ),
        ),
    ]
