# Generated by Django 4.2.4 on 2023-08-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0007_alter_post_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
    ]
