# Generated by Django 4.2.4 on 2023-08-10 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_bookingitem_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.booking'),
        ),
    ]
